### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by kellieotto** [Ji-Zhang/datacleanbot#7]
This issue is part of your [JOSS review](https://github.com/openjournals/joss-reviews/issues/1608).

I can't get the examples (in the README, and in the readthedocs example) to run. First, I had to pip install openml (as it is not installed via the requirements file). 

Then I get the following error: 
`TypeError: get_data() got an unexpected keyword argument 'return_attribute_names'`

**Comment by Ji-Zhang** [comment]
Thanks! `openml` has been updated. I just updated the README and the readthedocs example. It should work now.

**Comment by kthyng** [comment]
@kellieotto has this fixed the problem?

**Comment by kellieotto** [comment]
@Ji-Zhang @kthyng this fixed the original problem, but I am still not able to run examples. I get the following error (and have tried a few different openml datasets):

```
LoweringError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.StaticSetItem'>, X_hat[(slice(None, None, None), slice(None, None, None))] = $0.13)

File "../../../../../../opt/conda/lib/python3.6/site-packages/datacleanbot/bayesian/explain.py", line 355:
def predict_data(X, C, R, S,
    <source elided>
    X_hat = np.zeros((N, D))
    X_hat[:, :] = np.inf
    ^

[1] During: lowering "X_hat[(slice(None, None, None), slice(None, None, None))] = $0.13" at /opt/conda/lib/python3.6/site-packages/datacleanbot/bayesian/explain.py (355)
```

**Comment by Ji-Zhang** [comment]
Hi @kellieotto, may I ask what version of the library `numba` you are using? Thanks.

**Comment by kellieotto** [comment]
I'm using `numba 0.44.1`.

**Comment by Ji-Zhang** [comment]
I have deprecated the feature of detecting feature data type using the Bayesian method as too many dependencies there. I created a new clean virtual environment to test it and it works well. I hope it can work on your end now. Thank you.
